spring:
  application:
    name: korvo-to-anki-lemmatization


  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:vocabulary_builder.sqlite3
    hikari:
      auto-commit: false
  shell:
    interactive:
      enabled: true

nlp:
  annotators:
    - tokenize
    - pos
    - lemma

korvo-to-anki:
  async-type: vtcf

logging:
  level:
    ru.dankoy.*: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"

debug: false
